@startuml
start 
: Load node conf;
: Setup node Signature Key;
repeat: Node Connection 
: Load Comm Conf for node x;
: Establish GRPC connection with node x;
repeat while (more node?) is (yes)
->no;
repeat: Load plugins 
: Load plugin x;
repeat while (more plugin?) is (yes)
->no;
: Prepare Vault;
: Start REST to Server Client;
end
@enduml
